import { ColorModeScript } from '@chakra-ui/react';
import { Providers } from './Providers';
import ToasterContext from './context/ToasterContext';
import './globals.css';
import AuthContext from './context/AuthContext';
import { UrlsContextProvider } from './context/UrlsProvider';
import Navbar from './components/Navbar';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>
        <Providers>
          <AuthContext>
            <UrlsContextProvider>
              <Navbar />
              <ToasterContext />
              {children}
            </UrlsContextProvider>
          </AuthContext>
        </Providers>
      </body>
    </html>
  );
}

